apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: robusta-torch-1

resources:
- ../../base

# we need to generate a different ConfigMap per node, due to they have different content
configMapGenerator:
  - name: otel-agent
    files:
      - configs/otel-agent-celestia.yaml
      #- configs/otel-agent.yaml

images:
  - name: ghcr.io/jrmanes/svcwatchdog
    newTag: latest