---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: watchdog
  name: watchdog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watchdog
  template:
    metadata:
      labels:
        app: watchdog
    spec:
      serviceAccountName: watchdog
      containers:
        - name: watchdog
          image: ghcr.io/jrmanes/watchdog:SET-IT
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
          args:
            - ./watchdog
          env:
            - name: HTTP_PORT
              value: "8080"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: "20Mi"
              cpu: "20m"
            limits:
              memory: "50Mi"
              cpu: "50m"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
        - name: otel-agent
          image: otel/opentelemetry-collector-contrib:SET-IT
          command:
            - '/otelcol-contrib'
            - '--config=/conf/otel-agent.yaml'
          env:
            - name: GRAFANA_OTEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: grafana-otel-token
                  key: token
            - name: GRAFANA_OTEL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: grafana-otel-token
                  key: username
          volumeMounts:
            - name: otel-agent
              mountPath: "/conf/otel-agent.yaml"
              subPath: otel-agent.yaml
          ports:
            - name: prometheus-otel
              containerPort: 8888
            - name: prometheus
              containerPort: 9090
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - all
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              memory: 200Mi
      volumes:
        - name: otel-agent
          configMap:
            name: otel-agent