---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: watchdog
  name: watchdog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watchdog
  template:
    metadata:
      labels:
        app: watchdog
    spec:
      serviceAccountName: watchdog
      containers:
      - name: watchdog
        image: ghcr.io/jrmanes/watchdog:SET-IT
        imagePullPolicy: Always
        command:
          - /bin/sh
          - -c
        args:
          - ./watchdog
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
          - name: http
            containerPort: 8080
        resources:
          requests:
            memory: "50Mi"
            cpu: "20m"
          limits:
            memory: "100Mi"
            cpu: "100m"
      - name: otel-agent
        image: otel/opentelemetry-collector-contrib:0.71.0
        command:
          - '/otelcol-contrib'
          - '--config=/conf/otel-agent.yaml'
        volumeMounts:
          - name: otel-agent
            mountPath: "/conf/otel-agent.yaml"
            subPath: otel-agent-celestia.yaml
        ports:
          - name: prometheus-otel
            containerPort: 8888
          - name: prometheus
            containerPort: 9090
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            memory: 200Mi
      volumes:
        - name: otel-agent
          configMap:
            name: otel-agent
