---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: svcwatchdog
  name: svcwatchdog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svcwatchdog
  template:
    metadata:
      labels:
        app: svcwatchdog
    spec:
      volumes:
        - name: otel-agent
          configMap:
            name: otel-agent
      serviceAccountName: svcwatchdog
      containers:
      - name: svcwatchdog
        image: ghcr.io/jrmanes/svcwatchdog:latest
        #image: ghcr.io/jrmanes/svcwatchdog:SET-IT
        imagePullPolicy: Always
        command:
          - /bin/sh
          - -c
        args:
          - ./svcwatchdog
          #- ./svcwatchdog --configs-file /configs/configs.yaml
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
          - name: http
            containerPort: 8080
          - name: myapp-http
            containerPort: 9090
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "250Mi"
            cpu: "250m"
#        volumeMounts:
#        - name: configs
#          mountPath: "/configs"
#          readOnly: true
      - name: otel-agent
        image: otel/opentelemetry-collector-contrib:0.71.0
        command:
          - '/otelcol-contrib'
          - '--config=/conf/otel-agent.yaml'
        volumeMounts:
          - name: otel-agent
            mountPath: "/conf/otel-agent.yaml"
            subPath: otel-agent.yaml
        ports:
          - name: prometheus-otel
            containerPort: 8888
          - name: prometheus
            containerPort: 26660
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            # cpu: https://home.robusta.dev/blog/stop-using-cpu-limits
            memory: 200Mi