---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: watchdog
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: watchdog-role
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["list", "get", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "get", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: watchdog-rolebinding
subjects:
- kind: ServiceAccount
  name: watchdog
roleRef:
  kind: Role
  name: watchdog-role
  apiGroup: rbac.authorization.k8s.io
