---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svcwatchdog
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: svcwatchdog-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "get", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: svcwatchdog-rolebinding
subjects:
- kind: ServiceAccount
  name: svcwatchdog
roleRef:
  kind: Role
  name: svcwatchdog-role
  apiGroup: rbac.authorization.k8s.io
