---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: svcwatchdog
  name: svcwatchdog
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: svcwatchdog
  type: ClusterIP
