---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: svcwatchdog-metrics
  name: svcwatchdog-metrics
spec:
  selector:
    matchLabels:
      app: svcwatchdog-metrics
  targetLabels:
    - app
    - environment
    - network
    - type
    - chain-id
  endpoints:
    - port: prometheus