receivers:
  otlp:
    protocols:
      http:
        endpoint: "localhost:4318"

exporters:
  otlphttp:
#    auth:
#      authenticator: basicauth/otlp
    endpoint:  https://otlp-gateway-prod-us-central-0.grafana.net/otlp

processors:
  batch:
  memory_limiter:
    # 80% of maximum memory up to 2G
    limit_mib: 400
    # 25% of limit up to 2G
    spike_limit_mib: 100
    check_interval: 5s

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [otlphttp]
    traces:
      receivers: [otlp]
      exporters: [otlphttp]
      processors: [memory_limiter, batch]