receivers:
  otlp:
    protocols:
      http:
        endpoint: "localhost:4318"

exporters:
  otlphttp:
#    auth:
#      authenticator: basicauth/otlp
    endpoint:  https://otlp-gateway-prod-us-central-0.grafana.net/otlp

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [otlphttp]
    traces:
      receivers: [otlp]
      exporters: [otlphttp]
      processors: [batch]